name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: Reusable-workflow/.github/workflows/blank.yml@v2

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "hello world2"
