name: Call a reusable workflow
on:
  workflow_dispatch:

jobs:

  call-workflow1:
    uses: Thirthavathi-NR/Reusable-workflow/.github/workflows/blank.yml@main
    
  call-workflow2:
    uses: Thirthavathi-NR/Reusable-workflow/.github/workflows/workflow-two.yml@main
